inventory:
- source: DirectOwners
  items:
  - id: chadradams@outlook.com
    name: Chad Adams
    email: chadradams@outlook.com
    github: chadradams
    linkedin: https://www.linkedin.com/in/chadradams/
    phone: +1-818-808-5475
    location: Kansas City, MO
    title: Principal Software Engineer
  isProduction: false
