name: Generate Resume Formats

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACTIONS_PAT }}
    - name: Add Multiverse Repository
      run: |
        sudo add-apt-repository multiverse
        sudo apt-get update
    - name: Install Microsoft packages
      run: sudo apt-get install ttf-mscorefonts-installer
    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc
    - name: Install TeX Live
      run: |
        sudo apt-get install -y texlive-xetex
        sudo apt install fonts-ebgaramond
    - name: Convert Markdown to PDF
      run: pandoc README.md -o chadadams_resume.pdf --pdf-engine=xelatex -V mainfont="EB Garamond" -V fontsize=12pt
    - name: Convert Markdown to Word
      run: pandoc README.md -o chadadams_resume.docx -V mainfont="EB Garamond" -V  fontsize=12pt
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Chad Adams[bot]'
        git config --global user.email 'chadradams@users.noreply.github.com'
        git add chadadams_resume.pdf chadadams_resume.docx
        git commit -m 'Update resume formats'
        git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
        git push origin HEAD:main
    - name: Upload Documents
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: resume
        path: |
          chadadams_resume.pdf
          chadadams_resume.docx