name: Generate Resume Formats

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install pandoc texlive-xetex
    - name: Convert Markdown to PDF
      run: pandoc README.md -o chadadams_resume.pdf
    - name: Convert Markdown to Word
      run: pandoc README.md -o chadadams_resume.docx
    - name: Convert Markdown to RTF
      run: pandoc README.md -o chadadams_resume.rtf
    - name: Upload Documents
      uses: actions/upload-artifact@v3
      with:
        name: resume
        path: |
          chadadams_resume.pdf
          chadadams_resume.docx
          chadadams_resume.rtf