name: Generate Resume Formats

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc
    - name: Install TeX Live
      run: sudo apt-get install -y texlive-xetex
    - name: Convert Markdown to PDF
      run: pandoc README.md -o chadadams_resume.pdf
    - name: Convert Markdown to Word
      run: pandoc README.md -o chadadams_resume.docx
    - name: Convert Markdown to RTF
      run: pandoc README.md -o chadadams_resume.rtf
    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add chadadams_resume.pdf chadadams_resume.docx chadadams_resume.rtf
        git commit -m 'Update resume formats'
        git push
    - name: Upload Documents
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: |
          chadadams_resume.pdf
          chadadams_resume.docx
          chadadams_resume.rtf